site_name: MBASIC 5.21 Documentation
site_description: Complete documentation for MBASIC 5.21 interpreter - MBASIC-80 for CP/M implemented in Python
site_author: MBASIC Project Contributors
site_url: https://avwohl.github.io/mbasic

repo_name: avwohl/mbasic
repo_url: https://github.com/avwohl/mbasic
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - awesome-pages:
      filename: .pages
      collapse_single_pages: false
      strict: false

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: avwohl
      repo: mbasic
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
      toc_depth: 3

# Documentation structure
nav:
  - Home: index.md
  - Getting Started:
    - help/mbasic/getting-started.md
    - help/mbasic/features.md
    - help/mbasic/compatibility.md
  - User Guides:
    - user/QUICK_REFERENCE.md
    - user/INSTALL.md
    - user/INSTALLATION.md
    - Choosing Your UI: user/CHOOSING_YOUR_UI.md
    - UI Features: user/UI_FEATURE_COMPARISON.md
    - Settings: user/SETTINGS_AND_CONFIGURATION.md
    - Case Handling: user/CASE_HANDLING_GUIDE.md
    - File Formats: user/FILE_FORMAT_COMPATIBILITY.md
    - Sequential Files: user/sequential-files.md
    - Keyboard Shortcuts: user/keyboard-shortcuts.md
    - Tk Quick Start: user/TK_UI_QUICK_START.md
  - Help System:
    - help/index.md
    - MBASIC:
      - help/mbasic/index.md
      - help/mbasic/architecture.md
      - help/mbasic/extensions.md
      - help/mbasic/not-implemented.md
      - Implementation:
        - help/mbasic/implementation/string-allocation-and-garbage-collection.md
    - Common:
      - help/common/index.md
      - help/common/getting-started.md
      - help/common/debugging.md
      - help/common/editor-commands.md
      - help/common/settings.md
      - help/common/shortcuts.md
      - Examples:
        - help/common/examples.md
        - help/common/examples/hello-world.md
        - help/common/examples/loops.md
      - Compiler:
        - help/common/compiler/index.md
        - help/common/compiler/optimizations.md
    - Language Reference:
      - help/common/language.md
      - help/common/language/index.md
      - help/common/language/character-set.md
      - help/common/language/data-types.md
      - help/common/language/operators.md
      - help/common/language/variables.md
      - Statements:
        - help/common/language/statements/index.md
        - help/common/language/statements/auto.md
        - help/common/language/statements/call.md
        - help/common/language/statements/chain.md
        - help/common/language/statements/clear.md
        - help/common/language/statements/cload.md
        - help/common/language/statements/close.md
        - help/common/language/statements/cls.md
        - help/common/language/statements/common.md
        - help/common/language/statements/cont.md
        - help/common/language/statements/csave.md
        - help/common/language/statements/data.md
        - help/common/language/statements/def-fn.md
        - help/common/language/statements/def-usr.md
        - help/common/language/statements/defint-sng-dbl-str.md
        - help/common/language/statements/delete.md
        - help/common/language/statements/dim.md
        - help/common/language/statements/edit.md
        - help/common/language/statements/end.md
        - help/common/language/statements/erase.md
        - help/common/language/statements/err-erl-variables.md
        - help/common/language/statements/error.md
        - help/common/language/statements/field.md
        - help/common/language/statements/files.md
        - help/common/language/statements/for-next.md
        - help/common/language/statements/get.md
        - help/common/language/statements/gosub-return.md
        - help/common/language/statements/goto.md
        - help/common/language/statements/helpsetting.md
        - help/common/language/statements/if-then-else-if-goto.md
        - help/common/language/statements/input.md
        - help/common/language/statements/input_hash.md
        - help/common/language/statements/inputi.md
        - help/common/language/statements/kill.md
        - help/common/language/statements/let.md
        - help/common/language/statements/limits.md
        - help/common/language/statements/line-input.md
        - help/common/language/statements/list.md
        - help/common/language/statements/llist.md
        - help/common/language/statements/load.md
        - help/common/language/statements/lprint-lprint-using.md
        - help/common/language/statements/lset.md
        - help/common/language/statements/merge.md
        - help/common/language/statements/mid-assignment.md
        - help/common/language/statements/name.md
        - help/common/language/statements/new.md
        - help/common/language/statements/null.md
        - help/common/language/statements/on-error-goto.md
        - help/common/language/statements/on-gosub-on-goto.md
        - help/common/language/statements/open.md
        - help/common/language/statements/option-base.md
        - help/common/language/statements/out.md
        - help/common/language/statements/poke.md
        - help/common/language/statements/print.md
        - help/common/language/statements/printi-printi-using.md
        - help/common/language/statements/put.md
        - help/common/language/statements/randomize.md
        - help/common/language/statements/read.md
        - help/common/language/statements/rem.md
        - help/common/language/statements/renum.md
        - help/common/language/statements/reset.md
        - help/common/language/statements/restore.md
        - help/common/language/statements/resume.md
        - help/common/language/statements/rset.md
        - help/common/language/statements/run.md
        - help/common/language/statements/save.md
        - help/common/language/statements/setsetting.md
        - help/common/language/statements/showsettings.md
        - help/common/language/statements/stop.md
        - help/common/language/statements/swap.md
        - help/common/language/statements/system.md
        - help/common/language/statements/tron-troff.md
        - help/common/language/statements/wait.md
        - help/common/language/statements/while-wend.md
        - help/common/language/statements/width.md
        - help/common/language/statements/write.md
        - help/common/language/statements/writei.md
      - Functions:
        - help/common/language/functions/index.md
        - help/common/language/functions/abs.md
        - help/common/language/functions/asc.md
        - help/common/language/functions/atn.md
        - help/common/language/functions/cdbl.md
        - help/common/language/functions/chr_dollar.md
        - help/common/language/functions/cint.md
        - help/common/language/functions/cos.md
        - help/common/language/functions/csng.md
        - help/common/language/functions/cvi-cvs-cvd.md
        - help/common/language/functions/eof.md
        - help/common/language/functions/exp.md
        - help/common/language/functions/fix.md
        - help/common/language/functions/fre.md
        - help/common/language/functions/hex_dollar.md
        - help/common/language/functions/inkey_dollar.md
        - help/common/language/functions/inp.md
        - help/common/language/functions/input_dollar.md
        - help/common/language/functions/instr.md
        - help/common/language/functions/int.md
        - help/common/language/functions/left_dollar.md
        - help/common/language/functions/len.md
        - help/common/language/functions/loc.md
        - help/common/language/functions/lof.md
        - help/common/language/functions/log.md
        - help/common/language/functions/lpos.md
        - help/common/language/functions/mid_dollar.md
        - help/common/language/functions/mki_dollar-mks_dollar-mkd_dollar.md
        - help/common/language/functions/oct_dollar.md
        - help/common/language/functions/peek.md
        - help/common/language/functions/pos.md
        - help/common/language/functions/right_dollar.md
        - help/common/language/functions/rnd.md
        - help/common/language/functions/sgn.md
        - help/common/language/functions/sin.md
        - help/common/language/functions/space_dollar.md
        - help/common/language/functions/spc.md
        - help/common/language/functions/sqr.md
        - help/common/language/functions/str_dollar.md
        - help/common/language/functions/string_dollar.md
        - help/common/language/functions/tab.md
        - help/common/language/functions/tan.md
        - help/common/language/functions/usr.md
        - help/common/language/functions/val.md
        - help/common/language/functions/varptr.md
      - Appendices:
        - help/common/language/appendices/index.md
        - help/common/language/appendices/ascii-codes.md
        - help/common/language/appendices/error-codes.md
        - help/common/language/appendices/math-functions.md
    - UI Guides:
      - help/ui/index.md
      - CLI:
        - help/ui/cli/index.md
        - help/common/ui/cli/index.md
        - help/ui/cli/debugging.md
        - help/ui/cli/find-replace.md
        - help/ui/cli/settings.md
        - help/ui/cli/variables.md
      - Curses:
        - help/ui/curses/index.md
        - help/common/ui/curses/editing.md
        - help/ui/curses/editing.md
        - help/ui/curses/feature-reference.md
        - help/ui/curses/files.md
        - help/ui/curses/find-replace.md
        - help/ui/curses/getting-started.md
        - help/ui/curses/help-navigation.md
        - help/ui/curses/quick-reference.md
        - help/ui/curses/running.md
        - help/ui/curses/settings.md
        - help/ui/curses/variables.md
      - Tk:
        - help/ui/tk/index.md
        - help/common/ui/tk/index.md
        - help/ui/tk/feature-reference.md
        - help/ui/tk/features.md
        - help/ui/tk/getting-started.md
        - help/ui/tk/settings.md
        - help/ui/tk/tips.md
        - help/ui/tk/workflows.md
      - Web:
        - help/ui/web/index.md
        - help/ui/web/debugging.md
        - help/ui/web/features.md
        - help/ui/web/getting-started.md
        - help/ui/web/settings.md
        - help/ui/web/web-interface.md
      - Common:
        - help/ui/common/errors.md
        - help/ui/common/running.md
  - Library:
    - library/index.md
    - Games: library/games/index.md
    - Utilities: library/utilities/index.md
    - Education: library/education/index.md
    - Business: library/business/index.md
    - Electronics: library/electronics/index.md
    - Ham Radio: library/ham_radio/index.md
    - Data Management: library/data_management/index.md
    - Telecommunications: library/telecommunications/index.md
    - Demos: library/demos/index.md
  - Project Status: PROJECT_STATUS.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/avwohl/mbasic
  generator: false

# Extra CSS for BASIC code highlighting
extra_css:
  - stylesheets/extra.css

docs_dir: docs
site_dir: site

# Exclude files that conflict or shouldn't be in the site
# For end-user site: exclude dev docs from search index
exclude_docs: |
  README.md
  history/
  dev/
  future/
  design/
  external/
